DOMAINS = [
    # === SPORTS BETTING - GLOBAL ===
    "bet365.com","draftkings.com","fanduel.com","betway.com","williamhill.com",
    "betfair.com","paddypower.com","skybet.com","ladbrokes.com","coral.co.uk",
    "bwin.com","unibet.com","888sport.com","betvictor.com","boylesports.com",
    "sportingbet.com","betsson.com","nordicbet.com","casumo.com","mrgreen.com",
    "leovegas.com","bethard.com","speedy.bet","betclic.com","winamax.fr",
    "pmu.fr","zebet.fr","netbet.fr","betsson.com","neds.com.au",
    "sportsbet.com.au","tab.com.au","pointsbet.com.au","palmerbet.com","topsport.com.au",
    "bluebet.com.au","betr.com.au","elitebet.com.au","betmgm.com","caesarssportsbook.com",
    "pointsbet.com","barstoolsportsbook.com","wynn.bet","foxbet.com","betrivers.com",
    "sugarhouse.com","1xbet.com","melbet.com","22bet.com","betano.com",
    "interwetten.com","tipico.com","mybookie.ag","bovada.lv","betonline.ag",
    "sportsbetting.ag","intertops.eu","gtbets.eu","xbet.ag","bookmaker.eu",
    "matchbook.com","smarkets.com","betdaq.com","spreadex.com","marathonbet.com",
    "rabona.com","betamo.com","betinia.com","coolbet.com","grosvenorsports.com",
    "sportpesa.com","mozzartbet.com","betking.com","nairabet.com","bet9ja.com",
    "sportybet.com","betpawa.com","hollywoodbets.net","sunbet.co.za","10bet.co.za",
    "superbet.com","fortuna.com","sts.pl","lvbet.com","betcris.com",
    "tonybet.com","karamba.com","comeon.com","betsafe.com","rizk.com",
    "dunder.com","frank.casino","guts.com","mybet.com","bet-at-home.com",
    "sportium.es","codere.es","betfair.es","luckia.es","jonabet.com",
    "betfred.com","dafabet.com","sbobet.com","ibcbet.com","m88.com",
    "188bet.com","12bet.com","fun88.com","w88.com","v9bet.com",
    "bk8.com","ae888.com","hi88.com","jun88.com","kubet.io",
    "unibet.co.uk","unibet.se","unibet.de","unibet.fr","unibet.au",
    "bet365.es","bet365.it","bet365.de","bet365.fr","bet365.au",
    "bwin.it","bwin.fr","bwin.de","bwin.es","bwin.com.br",
    "pinnacle.com","pinnaclesports.com","betway.co.uk","betway.es","betway.it",
    "betway.de","betway.africa","betway.us","betway.co.za","betway.com.au",
    "1xbet.ng","1xbet.cm","1xbet.ke","1xbet.gh","1xbet.tz",
    "22bet.ng","22bet.ke","22bet.gh","22bet.cm","22bet.tz",
    "melbet.ng","melbet.ke","melbet.gh","melbet.cm","melbet.tz",
    "betway.ug","sportpesa.ke","odibets.com","betin.co.ke","bangbet.com",
    "merrybet.com","lionsbet.com","betboro.com","supabets.co.za","gbets.co.za",
    "worldsports.bet","betcity.ru","winline.ru","fonbet.ru","olimp.bet",
    "ligastavok.ru","pari.ru","bk-leon.ru","tennisi.ru","zenit.bet",
    "1xstavka.ru","betboom.ru","parimatch.com","vbet.com","parimatch.ru",
    "betmaster.io","betwinner.com","22bet.com","melbet.com","1xbet.com",
    "megapari.com","ivibet.com","betandyou.com","20bet.com","olybet.com",
    "betsafe.com","nordicbet.com","hajper.com","snabbare.com","highroller.com",
    "sunnyplayer.de","sunmaker.com","tipwin.com","interwetten.de","mybet.de",
    "winamax.es","codere.com.mx","sportium.com.mx","caliente.mx","vwin.com",
    "fb88.asia","bk8.com","w88.com","m88.com","fun88.asia",
    "88bola.com","asiabet.org","ibcbet.net","sbobet.eu","maxbet.com",
    "ibet44.com","3et.com","cwin.com","k8.io","vn88.com",
    "ta88.com","u888.bet","mocbai.com","kubet88.com","79king.net",
    "shbet.net","jun88.com","hi88.com","ae888.com","789bet.net",
    "go88.vin","rio66.net","fi88.homes","99ok.com","vin777.win",

    # === CASINO ===
    "888casino.com","videoslots.com","genesis-casino.com","wildz.com","lapalingo.com",
    "wintika.com","bizzo.casino","vulkan.bet","pinup.casino","1win.xyz",
    "mostbet.com","joocasino.com","jvspin.com","booi.com","bcasino.com",
    "turbico.com","fortunejack.com","betcoin.ag","cloudbet.com","nitrogen.sports",
    "stake.com","rollbit.com","roobet.com","gamdom.com","duelbits.com",
    "bc.game","bitstarz.com","mbitcasino.io","7bit.casino","katsubet.com",
    "oshi.io","jackpotcity.com","spin.casino","ruby.casino","casino.com",
    "888.com","casinoroom.com","svenbet.com","vegasoo.com","casinoeuro.com",
    "redbet.com","sunnyplayer.com","casinoheroes.com","casinoland.com","casinomaxi.com",
    "netbet.co.uk","betchan.com","playojo.com","slotsmillion.com","slotsmagic.com",
    "spinit.com","fastpay.casino","bao.casino","slotv.com","ggbet.com",
    "luckland.com","casimba.com","casino-x.com","slotty.com","playzee.com",
    "cashmo.co.uk","mfortune.co.uk","jackpotjoy.com","heart.bingo","foxy.bingo",
    "tombola.co.uk","wink.bingo","ladbrokes.com","coral.co.uk","williamhill.com",
    "betfair.com","paddypower.com","partycasino.com","casinoclub.com","druckgluck.de",
    "jackwinpalace.com","bonanzagame.com","slottica.com","betamo.com","gslot.com",
    "horus.casino","katsu.bet","apollo.bet","irishslots.com","lottoland.com",
    "lottoland.co.uk","health.casino","evobet.com","vegadream.com","casinobrango.com",
    "playbetr.com","casinonic.com","wazamba.com","amunra.com","maneki.casino",
    "tsars.com","gunsbet.com","casino-gods.com","casino-gods.com","omni.casino",
    "royalspins.com","lilibet.com","luckybird.io","megaslot.io","casinoin.io",
    "haz.casino","playfrank.com","casinofair.com","21casino.com","kingbilly.com",
    "casino-x.com","vulkanbet.com","goldenstar.io","helloween.casino","arlekino.casino",
    "flagman.bet","champion.casino","1xslots.com","casino-z.com","cosmolot.ua",
    "parimatch.ua","favbet.ua","vbet.ua","marathonbet.ua","winwin.ua",
    "izibet.com","sportaza.com","hpybet.com","powbet.com","wbet.biz",
    "indibet.com","10cric.com","parimatch.in","bet365.in","betway.in",
    "jeetwin.com","fun88.in","pure.win","casumo.in","royal.win",
    "betwinner.in","1xbet.in","melbet.in","22bet.in","megapari.in",
    "bluechip.io","bettilt.com","bons.com","biabet.com","mostbet.in",

    # === POKER ===
    "pokerstars.com","pokerstars.eu","pokerstars.net","pokerstars.es","pokerstars.it",
    "pokerstars.fr","pokerstars.de","pokerstars.pt","pokerstars.ro","pokerstars.bg",
    "888poker.com","888poker.es","888poker.it","888poker.pt","ggpoker.com",
    "ggpoker.eu","ggpoker.uk","partypoker.com","partypoker.eu","partypoker.us",
    "natural8.com","ipoker.com","winamax.fr","wsop.com","americas-cardroom.com",
    "bodog.eu","ignitioncasino.eu","borgatapoker.com","wptglobal.com","gpoker.com",
    "full-tilt-poker.com","betsson-poker.com","bet365poker.com","unibet-poker.com","bwin-poker.com",
    "pokerbaazi.com","adda52.com","pokerstars.in","9stacks.com","spartan-poker.com",

    # === SPORTS NEWS & DATA ===
    "espn.com","sports.yahoo.com","bleacherreport.com","theathletic.com","cbssports.com",
    "foxsports.com","nbcsports.com","si.com","sportingnews.com","skysports.com",
    "bbc.co.uk","goal.com","90min.com","givemesport.com","talksport.com",
    "eurosport.com","sport1.de","kicker.de","spox.com","ran.de",
    "marca.com","mundodeportivo.com","as.com","sport.es","abc.es",
    "lequipe.fr","maxifoot.fr","footmercato.net","sofoot.com","butfootballclub.fr",
    "gazzetta.it","corrieredellosport.it","tuttosport.com","calciomercato.com","football-italia.net",
    "record.pt","abola.pt","ojogo.pt","maisfutebol.iol.pt","zerozero.pt",
    "livescore.com","sofascore.com","flashscore.com","soccerway.com","whoscored.com",
    "transfermarkt.com","transfermarkt.de","transfermarkt.co.uk","soccerstats.com","oddsportal.com",
    "oddschecker.com","betbrain.com","statsperform.com","wyscout.com","fbref.com",
    "basketball-reference.com","baseball-reference.com","pro-football-reference.com","hockey-reference.com","sports-reference.com",
    "soccervista.com","forebet.com","predictz.com","winnerbet.com","betexplorer.com",
    "fussballdaten.de","weltfussball.de","kicker.de","transfermarkt.at","transfermarkt.es",
    "legaseriea.it","premierleague.com","laliga.com","bundesliga.com","ligue1.com",
    "eredivisie.nl","primeiraliga.pt","superliga.dk","allsvenskan.se","eliteserien.no",
    "mls.com","ligamx.net","brasileirao.com.br","argentinafootball.com","copalibre.com",
    "rsssf.com","11v11.com","soccerbase.com","soccernet.espn.com","football-lineups.com",
    "soccerway.com","resultados-futbol.com","livescore.biz","livescore.in","livescore.net",
    "flashscore.com.br","flashscore.es","flashscore.de","flashscore.fr","flashscore.pl",
    "sportytrader.com","nowgoal.com","goaloo.com","betstudy.com","tipsscore.com",
    "scorebat.com","scoreboard.com","sportsmole.co.uk","sportsmole.es","goals.com",
    "statsinsider.com.au","sportsbettingdime.com","sportsbookreview.com","thelines.com","covers.com",

    # === FOOTBALL CLUBS - PREMIER LEAGUE ===
    "manutd.com","chelsea.com","arsenal.com","liverpool.com","mancity.com",
    "tottenhamhotspur.com","leicestercity.com","everton.com","westham.co.uk","aston-villa.co.uk",
    "crystalpalace.co.uk","brentfordfc.com","fulhamfc.com","brightonandhovealbion.com","nottinghamforest.com",
    "wolvesfc.com","newcastleunited.com","burnley.com","lutontown.co.uk","sheffieldunited.com",
    "sunderland.com","middlesbrough.com","stokecity.com","coventrychampion.co.uk","wba.co.uk",
    "swanseacity.com","cardiffcityfc.co.uk","boro-fc.co.uk","bristolcity.co.uk","qpr.co.uk",

    # === FOOTBALL CLUBS - LA LIGA ===
    "realmadrid.com","fcbarcelona.com","atleticomadrid.com","villarreaicf.com","athleticclub.eus",
    "realsociedad.com","betisbalompie.es","sevilla.com","rcdmallorca.com","osasuna.es",
    "valenciacf.com","getafecf.com","rcdespanyol.com","celtavigo.net","girona.cat",
    "realvalladolid.es","racingdesantander.com","lapalmas.com","cadizclub.com","almeria.es",

    # === FOOTBALL CLUBS - SERIE A ===
    "juventus.com","acmilan.com","inter.it","asroma.com","sslazio.it",
    "atalanta.com","fiorentina.it","napoli.it","torino.it","sampdoria.it",
    "genoafc.it","udinese.it","hellasveronafc.it","bolognfc.it","monacofc.com",
    "empolicolcio.it","sassuolo.it","lecce.com","frosinone.it","cagliari.it",

    # === FOOTBALL CLUBS - BUNDESLIGA ===
    "fcbayern.com","borussia-dortmund.de","bayer04.de","rb-leipzig.de","gladbach.de",
    "eintracht-frankfurt.de","wolfsburg.de","hoffenheim.de","freiburg.de","hertha.de",
    "schalke04.de","werder.de","augsburg.de","mainz05.de","vfbstuttgart.de",
    "1fc-koeln.de","arminia.de","vfl-bochum.de","darmstadt98.de","heidenheim.de",

    # === FOOTBALL CLUBS - LIGUE 1 ===
    "psg.fr","olympique-et-lyonnais.com","stade-rennais.com","ogcnice.com","girondins.com",
    "losc.fr","asse.fr","fcnantes.com","staderennais.com","smcaen.fr",
    "metz.fr","stade-de-reims.fr","montpellier-hsc.fr","rcstrasbourg.fr","toulouse-fc.fr",
    "clermontfoot63.com","ajaccio-football.com","auxerre.com","angers-sco.fr","stademalherbe.fr",

    # === FOOTBALL CLUBS - OTHER EUROPE ===
    "ajax.nl","feyenoord.nl","psv.nl","benfica.pt","sporting.pt",
    "fcporto.pt","celtic.net","rangers.co.uk","anderlecht.be","clubbrugge.be",
    "galatasaray.org","fenerbahce.org","besiktas.com.tr","trabzonspor.org","bursaspor.org",
    "cska.ru","spartak.ru","zenit.ru","lokomotiv.ru","dynamo.ru",
    "shakhtar.com","dynamo.ua","sfck.ua","vorskla.poltava.ua","desna.ua",
    "fcmidtjylland.dk","fccopenhagen.dk","broendby.com","aabfc.dk","odensebk.dk",
    "iffk.se","aik.se","hammarby.se","djurgarden.se","malmoiff.se",
    "rosenborg.no","moldefc.no","vif.no","sarpsborg08.no","tromsoe.no",
    "hifk.fi","hik.fi","vps.fi","ilves.fi","inter.fi",
    "redsportsclub.com","slbenfica.pt","vitiória.pt","scbraga.pt","vitoria.pt",
    "fcbasle.ch","fcbern.ch","gcz.ch","fcstgallen.ch","lausanne-sport.ch",
    "salzburg.at","rapidwien.at","austriawien.at","wolfsbergerathletik.at","lask.at",
    "rsca.be","standardliege.com","krc-genk.be","gantoise.be","cerclebrugge.be",

    # === FOOTBALL CLUBS - AMERICAS ===
    "flamengo.com.br","corinthians.com.br","palmeiras.com.br","saopaulofc.net","gremio.net",
    "internacional.com.br","atletico.com.br","cruzeiro.com.br","botafogo.com.br","fluminense.com.br",
    "bocarjuniors.com.ar","riverplate.com.ar","sanlorenzo.com.ar","racingclub.com.ar","independiente.com.ar",
    "chivas.com.mx","americafutbol.com.mx","cruzazul.com.mx","tigres.com.mx","monterrey.com.mx",
    "ldu.com.ec","nacional.com.uy","penarol.org.uy","colo-colo.cl","universidadde-chile.cl",
    "lafc.com","lagalaxy.com","nycfc.com","atlantaunited.com","seattlesounders.com",
    "portlandtimbers.com","orlandocity.com","nycfc.com","redubls.com","nyrb.com",

    # === NATIONAL TEAMS ===
    "fifa.com","uefa.com","concacaf.com","conmebol.com","caf.online",
    "the-afc.com","oceaniafootball.com","safa.net","fourfourtwo.com","worldfootball.net",
    "worldsoccer.com","planetworldcup.com","rsssf.org","11v11.com","historical-lineups.com",

    # === NBA / BASKETBALL ===
    "nba.com","nbadleague.com","euroleague.net","fiba.basketball","realgm.com",
    "basketball-reference.com","draftexpress.com","landofbasketball.com","justsportsstats.com","tankathon.com",
    "celtics.com","lakers.com","warriors.com","nets.com","knicks.com",
    "heat.com","bucks.com","sixers.com","suns.com","nuggets.com",
    "mavericks.com","grizzlies.com","hawks.com","bulls.com","cavaliers.com",
    "blazers.com","spurs.com","jazz.com","pelicans.com","hornets.com",
    "timberwolves.com","raptors.com","magic.com","pistons.com","pacers.com",
    "kings.com","thunder.com","rockets.com","clippers.com","wizards.com",

    # === NFL ===
    "nfl.com","patriots.com","packers.com","cowboys.com","chiefs.com",
    "49ers.com","seahawks.com","rams.com","ravens.com","steelers.com",
    "giants.com","eagles.com","bears.com","falcons.com","buccaneers.com",
    "saints.com","vikings.com","lions.com","broncos.com","raiders.com",
    "chargers.com","bengals.com","browns.com","texans.com","colts.com",
    "jaguars.com","titans.com","bills.com","dolphins.com","jets.com",
    "commanders.com","cardinals.com","panthers.com","niners.com","falcons.com",

    # === MLB ===
    "mlb.com","yankees.com","redsox.com","cubs.com","dodgers.com",
    "giants.com","astros.com","braves.com","cardinals.com","bluejays.com",
    "mets.com","phillies.com","nationals.com","mariners.com","athletics.com",
    "angels.com","rangers.com","tigers.com","indians.com","twins.com",
    "royals.com","whitesox.com","brewers.com","rockies.com","padres.com",
    "marlins.com","orioles.com","rays.com","reds.com","pirates.com",

    # === NHL ===
    "nhl.com","mapleleafs.com","canadiens.com","bruins.com","rangers.com",
    "penguins.com","capitals.com","blackhawks.com","redwings.com","oilers.com",
    "flames.com","canucks.com","jets.com","blues.com","stars.com",
    "avalanche.com","golden-knights.com","lightning.com","panthers.com","sabres.com",
    "senators.com","hurricanes.com","blue-jackets.com","wild.com","ducks.com",
    "sharks.com","kings.com","coyotes.com","devils.com","islanders.com",

    # === TENNIS ===
    "atptour.com","wtatennis.com","itftennis.com","ustopen.org","wimbledon.com",
    "rolandgarros.com","australianopen.com","tennistv.com","tennisabstract.com","ultimatetennisstatistics.com",
    "live-tennis.eu","tennisexplorer.com","sofascore.com","flashscore.com","livescore.in",
    "tennistemple.com","tennisnow.com","tennis-x.com","tennisworldusa.org","tennishead.net",

    # === HORSE RACING ===
    "attheraces.com","racingpost.com","timeform.com","thoroughbreddailynews.com","bloodhorse.com",
    "horseracingnation.com","equibase.com","tvg.com","xpressbet.com","twinspires.com",
    "brisnet.com","betamerica.com","nyra.com","churchill-downs.com","keeneland.com",
    "santaanita.com","gulfstreampark.com","del-mar.com","belmontstakes.com","preakness.com",
    "sportinglife.com","racing-post.mobi","racenet.com.au","punters.com.au","tab.com.au",

    # === FORMULA 1 / MOTORSPORT ===
    "formula1.com","motogp.com","supercars.com","indycar.com","worldrx.com",
    "nascar.com","imsa.com","wrc.com","fiawec.com","fia.com",
    "motorsport.com","autosport.com","crash.net","racefans.net","f1technical.net",
    "pitpass.com","grandprix.com","f1news.ru","f1i.com","planetf1.com",
    "mercedesamgf1.com","redbullracing.com","ferrari.com","mclaren.com","alpine-cars.co.uk",
    "astonmartinf1.com","williams.com","haasf1team.com","alfaomeo.com","alphatauri.com",

    # === BOXING / MMA ===
    "ufc.com","bellator.com","one.fc","boxing247.co.uk","worldboxingassociation.com",
    "ibf-usba-boxing.com","wboboxing.com","wbc.com","boxingscene.com","eastsideboxing.com",
    "secsportingnews.com","thaboxingvoice.com","fightnews.com","boxrec.com","compubox.com",
    "tapology.com","sherdog.com","mmajunkie.com","mmafighting.com","bloodyelbow.com",
    "lowkickmma.com","mmaweekly.com","mma-core.com","mmamania.com","cagepotato.com",

    # === CRICKET ===
    "espncricinfo.com","cricbuzz.com","icc-cricket.com","ecb.co.uk","cricket.com.au",
    "bcci.tv","pcboard.com.pk","cricketwestindies.org","zimcricket.org","srilankacricket.lk",
    "cricketireland.ie","kes.co.ke","afghanistan-cricket.com","nepal.cricket.com","tigers.com.bd",
    "howstat.com","cricketarchive.com","cricinfo.com","cricket365.com","sky.cricket",

    # === RUGBY ===
    "rugbyworldcup.com","espnscrum.com","rugbypass.com","ultimaterugby.com","itsrugby.co.uk",
    "worldrugby.org","premiershinrugby.com","pro14rugby.com","rainbowcup.rugby","superrugby.com",
    "englandrugby.com","lionsrugby.com","allblacks.com","wallabies.rugby","springboks.rugby",
    "therugbysite.com","rugbydump.com","offsideline.com","rugbyinsider.com","leftfootforward.rugby",

    # === CYCLING ===
    "cyclingnews.com","velonews.com","cyclingweekly.com","cycling.today","pezcyclingnews.com",
    "firstcycling.com","procyclingstats.com","letour.fr","giroditalia.it","lavuelta.es",
    "paris-roubaix.fr","liege-bastogne-liege.be","tourdesuisse.ch","criteriumdudaluphiné.com","strade-bianche.it",
    "uci.org","teamsky.com","teamjumbovisma.com","deceuninck-quickstep.com","ag2rcitroen.team",

    # === GOLF ===
    "pgatour.com","europeantour.com","lpgatour.com","masters.com","usopen.com",
    "opengolf.com","pga.com","rydercup.com","presidents-cup.com","worldgolfchampionships.com",
    "golfweek.com","golfdigest.com","golf.com","golfchannel.com","golfmagic.com",
    "bunkered.co.uk","worldwide-golf-brands.com","golf365.com","golfwrx.com","swingbyswing.com",

    # === ATHLETICS / OLYMPICS ===
    "worldathletics.org","athletics.org.uk","usatf.org","european-athletics.org","olympic.org",
    "paralympic.org","fina.org","swimming.org","worldaquatics.com","gymnastics.org",
    "worldarchery.sport","worldrowing.com","worldsailing.org","worldcanoe.org","worldtriathlon.org",
    "worldweightlifting.org","worldjudo.org","unitedworldwrestling.org","worldboxing.sport","worldfencing.org",
    "worldskate.org","worldcurling.org","worldbiathlon.com","luge.ws","bsf-biathlon.com",

    # === ESPORTS ===
    "faceit.com","hltv.org","liquipedia.net","dotabuff.com","opendota.com",
    "op.gg","u.gg","lolalytics.com","gol.gg","vlr.gg",
    "tracker.gg","aligulac.com","sc2replaystats.com","battlefy.com","toornament.com",
    "challonge.com","esportal.com","gamersclub.com.br","99damage.de","esea.net",
    "upcomer.com","dexerto.com","dbltap.com","dot.esports","unikrn.com",
    "luckbox.com","thunderpick.io","midnite.com","arcanebet.com","gg.bet",
    "betway.gg","rivalry.com","csgoempire.com","hellcase.com","csgopolygon.com",
    "ggdrop.com","skinclub.com","csgoskins.gg","gamdom.com","wbskins.com",
    "twist.tv","esports.bet","esportsheadlines.com","esportsobserver.com","newzoo.com",

    # === FANTASY SPORTS ===
    "sportsline.com","vegasinsider.com","rotowire.com","rotogrinders.com","fantasypros.com",
    "sleeper.app","underdog.io","prizepicks.com","superdraft.com","fleaflicker.com",
    "numberfire.com","4for4.com","fftoday.com","footballguys.com","dynastyleaguefootball.com",
    "myfantasyleague.com","fantasyfootballcalculator.com","fantasydata.com","fantasysharks.com","cbssports.com",
    "draftsharks.com","bestball10s.com","supremedraft.com","underdogfantasy.com","nfl.com",
    "yahoo.com","espn.com","rtssports.com","nfldraftscout.com","drafttek.com",

    # === CASINO GAME PROVIDERS ===
    "netent.com","playtech.com","microgaming.co.uk","evolution.com","pragmaticplay.com",
    "nolimitcity.com","hacksaw.io","pushgaming.com","relax-gaming.com","blueprintgaming.com",
    "nextgen.co.uk","isoftbet.com","betsoft.com","thunderkick.com","playngo.com",
    "quickspin.com","yggdrasil.com","elk-studios.com","stakelogic.com","redtiger.com",
    "iron-dog-studio.com","slotmill.com","bgaming.com","kalamba.games","rabcat.com",
    "booming-games.com","wazdan.com","spinomenal.com","amatic.com","greentube.com",
    "kajot.com","octavian.com","playson.com","endorphina.com","swintt.com",
    "augustgaming.com","gametech.eu","rtg-slots.com","rival.com","saucify.com",
    "topgame.ag","betonstrike.com","1x2gaming.com","oryx-gaming.com","felt.com",

    # === CASINO REVIEW / AFFILIATE ===
    "casinoguru.com","askgamblers.com","casinomeister.com","thepogg.com","latestcasinobonuses.com",
    "casinoreviews.com","vegasslotsonline.com","onlinecasinoground.com","casinobee.com","bonusfinder.com",
    "nodepositcodes.com","casino.org","nodepositbonus.cc","gamblinginsider.com","casinobonusca.com",
    "casinosanalyzer.com","casinosnoop.com","casinolistings.com","casinoradar.co.uk","slotjava.it",
    "casinos.de","casinos.fr","casinos.es","casinos.it","casinobonuses.io",
    "newcasinos.com","newcasinos.uk","newcasinos.me","newcasinos.org","bestcasinos.com",
    "top10casinos.com","top10casinosites.net","top10onlinecasinos.com","which-casino.com","casinority.com",
    "bojoko.com","slotscalendar.com","slotcatalog.com","bigwinboard.com","slotsource.com",
    "casinogrounds.com","casinofreak.com","kasinokamu.com","kasinohai.com","kasinobernie.com",
    "bestuscasinos.org","usacasinos.com","casinousa.com","online-casinos.com","realmoneyaction.com",

    # === GAMBLING REGULATION ===
    "gamblingcommission.gov.uk","mga.org.mt","egba.eu","rgaoc.org","begambleaware.org",
    "gamcare.org.uk","gamblersanonymous.org","ncpgambling.org","responsiblegambling.org","iagr.org",
    "agcc.gl","kahnawake.com","alderney.gg","isle-of-man.com","gov.je",

    # === LOTTERY ===
    "lotterysambad.com","national-lottery.co.uk","euro-millions.com","lottoland.com","lotteryresults.ie",
    "nlcb.co.tt","national-lottery.ie","fdj.fr","lotto.de","loterianacional.es",
    "lotterie-intl.com","lottopark.com","lottosend.com","theLotter.com","lotto247.com",
    "giochiforzabuona.it","gioco24.it","sisal.it","snaitech.it","lottomatica.it",
    "camelot.co.uk","health-lottery.com","postcode-lottery.com","peoples-postcode.com","lotto.co.uk",

    # === SPORTS STREAMING ===
    "dazn.com","espnplus.com","peacocktv.com","tennistv.com","nba.com",
    "nfl.com","nhl.com","mlb.tv","watchespn.com","bt.com",
    "sky.com","btsport.com","beinsports.com","eleven-sports.com","laola1.tv",
    "sport.tv","sporttv.pt","teledeporte.es","tdp.es","sportklub.rs",
    "arena.tv","eurosport.com","motorsport.tv","motorsport.com","f1tv.com",

    # === MISC SPORTS SITES ===
    "volleyball.world","fivb.com","worldathleticscoaching.org","swimmingworld.com","usaswimming.org",
    "surfing.com","worldsurfleague.com","redbull.com","redbullstratos.com","redbullracing.com",
    "boardsport-source.com","skateboarding.transworld.net","bmx.transworld.net","motocross.transworld.net","surfline.com",
    "pgatour.com","lpgatour.com","dgcoursereview.com","pdga.com","discgolf.com",
    "darts501.com","dartsdatabase.co.uk","dartsnews.com","dartconnect.com","pdc.tv",
    "snooker.org","worldsnooker.com","147.com","snookerscores.net","snookerhq.com",
    "americasbowling.com","pba.com","bowl.com","tenpinbowling.org","worldbowling.org",

    # === MORE BETTING SITES ===
    "betcart.com","betsson.es","betsson.it","betsson.de","betsson.pl",
    "betsson.ro","betsson.ee","betsson.lv","betsson.lt","betsson.gr",
    "bet365.gr","bet365.ro","bet365.bg","bet365.hu","bet365.cz",
    "unibet.ro","unibet.hr","unibet.pl","unibet.hu","unibet.cz",
    "betfair.ro","betfair.pl","betfair.gr","betfair.hu","betfair.cz",
    "williamhill.es","williamhill.it","williamhill.ro","williamhill.pl","williamhill.gr",
    "marathonbet.co.uk","marathonbet.de","marathonbet.pl","marathonbet.ro","marathonbet.gr",
    "betway.it","betway.be","betway.pl","betway.ro","betway.pt",
    "betway.ng","betway.gh","betway.tz","betway.zm","betway.mz",
    "10bet.com","10bet.co.uk","10bet.eu","10bet.it","10bet.de",
    "mrgreen.de","mrgreen.it","mrgreen.fi","mrgreen.no","mrgreen.at",
    "leovegas.de","leovegas.it","leovegas.fi","leovegas.no","leovegas.at",
    "casumo.de","casumo.it","casumo.fi","casumo.no","casumo.es",
    "comeon.se","comeon.fi","comeon.no","comeon.de","comeon.at",
    "betsafe.se","betsafe.fi","betsafe.no","betsafe.de","betsafe.at",
    "betclic.pl","betclic.it","betclic.es","betclic.pt","betclic.de",
    "superbet.ro","superbet.pl","superbet.bg","superbet.hr","superbet.rs",
    "fortuna.ro","fortuna.bg","fortuna.hu","fortuna.cz","fortuna.sk",
    "betano.gr","betano.ro","betano.pt","betano.bg","betano.cz",
    "parimatch.kz","parimatch.by","parimatch.uz","parimatch.ua","parimatch.ge",
    "1xbet.uz","1xbet.kz","1xbet.by","1xbet.az","1xbet.ge",
    "melbet.uz","melbet.kz","melbet.by","melbet.az","melbet.ge",
    "betwinner.uz","betwinner.kz","betwinner.by","betwinner.az","betwinner.ge",
    "mostbet.uz","mostbet.kz","mostbet.by","mostbet.az","mostbet.ge",
    "1win.kz","1win.uz","1win.by","1win.az","1win.ge",
    "vbet.kz","vbet.uz","vbet.by","vbet.az","vbet.ge",
    "spinbetter.com","slothunter.com","fresh.casino","jet.casino","starda.casino",
    "izzi.casino","daddy.casino","cat.casino","gama.casino","volna.casino",
    "leon.bet","hit.casino","lucky.casino","gold.casino","king.casino",
    "ace.casino","wild.casino","mega.casino","prime.casino","vip.casino",
    "royal.casino","grand.casino","hot.casino","fast.casino","rich.casino",
    "joker.casino","dragon.casino","tiger.casino","lion.casino","wolf.casino",
    "vulkanbet.de","vulkanvegas.com","vulkanvegas.de","goldenstar.io","flagman.bet",
    "champion.casino","1xslots.com","casino-z.com","izibet.com","sportaza.com",
    "hpybet.com","powbet.com","wbet.biz","indibet.com","10cric.com",
    "parimatch.in","betway.in","jeetwin.com","fun88.in","pure.win",
    "betwinner.in","1xbet.in","melbet.in","22bet.in","megapari.in",
    "bluechip.io","bettilt.com","bons.com","biabet.com","mostbet.in",
    "casinoroom.se","casinoroom.fi","casinoroom.no","casinoroom.de","vegasoo.de",
    "casinoeuro.se","casinoeuro.fi","redbet.se","redbet.fi","redbet.no",
    "sunnyplayer.at","sunnyplayer.ch","sunmaker.at","sunmaker.ch","tipwin.de",
    "netbet.de","netbet.fr","netbet.ro","netbet.it","netbet.es",
    "jackpotcity.co.za","jackpotcity.eu","jackpotcity.com.au","jackpotcity.ca","jackpotcity.co.nz",
    "playojo.se","playojo.fi","playojo.no","playojo.de","playojo.at",
    "slotsmillion.se","slotsmillion.fi","slotsmillion.no","slotsmillion.de","videoslots.se",
    "videoslots.fi","videoslots.no","videoslots.de","21casino.de","21casino.fi",
    "wazamba.de","amunra.de","tsars.de","gunsbet.de","lilibet.de",
    "fortunejack.de","cloudbet.de","stake.de","rollbit.de","roobet.de",
    "gamdom.de","duelbits.de","bitstarz.de","mbitcasino.de","7bit.casino.de",

    # === MORE FOOTBALL CLUBS ===
    "seriea.it","ligue1.fr","eredivisie.nl","primeiraliga.pt","jupilerleague.be",
    "superleague.gr","ekstraklasa.net","fortuna-liga.cz","hnl.hr","superliga.dk",
    "allsvenskan.se","eliteserien.no","veikkausliiga.fi","liiga.fi","phl.fi",
    "fcmidtjylland.dk","fccopenhagen.dk","broendby.com","aabfc.dk","odensebk.dk",
    "redsportsclub.com","scbraga.pt","vitoria.pt","fcbasle.ch","fcbern.ch",
    "gcz.ch","fcstgallen.ch","salzburg.at","rapidwien.at","austriawien.at",
    "rsca.be","standardliege.com","krc-genk.be","gantoise.be","cerclebrugge.be",
    "shakhtar.com","dynamo.ua","sfck.ua","rosenborg.no","moldefc.no",
    "iffk.se","aik.se","hammarby.se","djurgarden.se","malmoiff.se",
    "flamengo.com.br","corinthians.com.br","palmeiras.com.br","saopaulofc.net","gremio.net",
    "internacional.com.br","atletico.com.br","cruzeiro.com.br","botafogo.com.br","fluminense.com.br",
    "bocarjuniors.com.ar","riverplate.com.ar","sanlorenzo.com.ar","racingclub.com.ar","independiente.com.ar",
    "chivas.com.mx","americafutbol.com.mx","cruzazul.com.mx","tigres.com.mx","monterrey.com.mx",
    "lafc.com","lagalaxy.com","nycfc.com","atlantaunited.com","seattlesounders.com",
    "portlandtimbers.com","orlandocity.com","nyrb.com","crystalpalace.co.uk","brentfordfc.com",
    "fulhamfc.com","brightonandhovealbion.com","nottinghamforest.com","wolvesfc.com","newcastleunited.com",
    "wolverhamptonwanderers.co.uk","sheffield-wednesday.co.uk","sheffieldunited.com","wba.co.uk","coventrychampion.co.uk",

    # === SPORTS ORGS ===
    "ncaa.com","nba.com","nfl.com","nhl.com","mlb.com",
    "wnba.com","nwsl.com","nasl.com","usl.com","concacafleague.com",
    "fiba.basketball","euroleaguewomen.com","fibaeuropecup.com","fibachampionsleague.com","fibaeurope.com",
    "ittf.com","bwf.org","psaworldtour.com","worldarchery.sport","worldkarate.is",
    "ijf.org","uww.org","worldboxing.sport","worldtaekwondo.org","worldshootingsport.org",
    "modernpentathlon.org","worldtriathlon.org","worldrowing.com","worldsailing.org","worldcanoe.org",
    "ihf.info","eurohandball.com","handball-bundesliga.de","beachsoccer.com","bsww.com",
    "padel.com","tabletennisengland.co.uk","squashsite.co.uk","fie.org","britishfencing.com",
    "worldskate.org","worldcurling.org","worldbiathlon.com","luge.ws","bsf-biathlon.com",
    "uci.org","worldathletics.org","fina.org","gymnastics.org","olympic.org",
    "darts501.com","dartsdatabase.co.uk","dartsnews.com","pdc.tv","dartconnect.com",
    "snooker.org","worldsnooker.com","snookerscores.net","snookerhq.com","147.com",

    # === FANTASY / DFS ===
    "myfantasyleague.com","fantasydata.com","fantasysharks.com","draftsharks.com","bestball10s.com",
    "supremedraft.com","underdogfantasy.com","drafttek.com","nfldraftscout.com","rtssports.com",
    "fantasyleaguemanager.co.uk","fantasy.premierleague.com","fantasyfootball.co.uk","fplstatistics.com","fplreview.com",
    "ffhive.com","livefpl.net","fplgameweek.com","fantasyfootballfix.com","fplstatman.co.uk",

    # === HORSE RACING EXTRA ===
    "belmontstakes.com","preakness.com","sportinglife.com","racenet.com.au","punters.com.au",
    "racingandsports.com.au","racingaustralia.horse","thoroughbredaustralia.com","newmarketracecourses.co.uk","ascot.co.uk",
    "cheltenham.co.uk","york-racecourse.co.uk","goodwood.com","epsom-racecourse.co.uk","aintree.co.uk",
    "haydock-park.co.uk","chester-races.co.uk","newbury-racecourse.co.uk","leicester-racecourse.co.uk","nottingham-racecourse.co.uk",

    # === LOTTERY ===
    "national-lottery.co.uk","euro-millions.com","lottoland.com","lotteryresults.ie","fdj.fr",
    "lotto.de","loterianacional.es","theLotter.com","lotto247.com","lottosend.com",
    "health-lottery.com","postcode-lottery.com","peoples-postcode.com","lotto.co.uk","camelot.co.uk",
    "sisal.it","snaitech.it","lottomatica.it","gioco24.it","lotterysambad.com",

    # === SPORTS STREAMING ===
    "dazn.com","espnplus.com","peacocktv.com","tennistv.com","mlb.tv",
    "watchespn.com","bt.com","btsport.com","beinsports.com","eleven-sports.com",
    "laola1.tv","sport.tv","sporttv.pt","tdp.es","sportklub.rs",
    "arena.tv","motorsport.tv","f1tv.com","ufc.tv","bellator.tv",
    "nbatvlive.com","nhltv.com","nfllive.com","mlblive.com","wnbalive.com",

    # === MORE CASINO / GAMBLING ===
    "pokerstarscasino.com","888casino.es","888casino.it","888casino.de","888casino.ro",
    "partycasino.es","partycasino.it","partycasino.de","casinoclub.de","druckgluck.de",
    "jackwinpalace.com","bonanzagame.com","slottica.com","gslot.com","horus.casino",
    "katsu.bet","apollo.bet","irishslots.com","lottoland.de","evobet.com",
    "vegadream.com","casinobrango.com","playbetr.com","casinonic.com","maneki.casino",
    "casino.de","casino.fr","casino.it","casino.es","casino.nl",
    "casino.pl","casino.ru","casino.ua","casino.ro","casino.hu",
    "online-casino.de","onlinecasino.de","online-casino.fr","online-casino.it","online-casino.es",
    "bestcasino.de","bestcasino.fr","bestcasino.it","bestcasino.es","bestcasino.nl",
    "topkasino.com","topcasino.com","topbet.com","topslots.com","topgames.com",
    "slotpark.com","slotpark.de","slotpark.fr","slotpark.it","slotpark.es",
    "slotland.com","slotland.eu","slotland.de","slotland.fr","slotland.it",
    "slotjoint.com","slotnuts.com","slotbox.com","slotboss.co.uk","slotfruity.com",
    "slotstars.com","slotjar.com","slotpages.com","slotsanctuary.com","slotsheaven.com",
    "slotsmith.com","slotsmash.com","slotspalace.com","slotsplusbonus.com","slotsroom.com",
    "playmillion.com","playfrank.com","playfortuna.com","playgrand.com","playamo.com",
    "playclub.com","playslots.com","playcasinozone.com","playbetr.com","playboom.com",
    "casinofloor.com","casinotropez.com","casinoroom.com","casinoland.com","casinomax.com",
    "casinopop.com","casinosieger.de","casinotest.de","casino-bonus.de","casino-check.de",
    "casinoadvice.com","casinoalpha.com","casinobest.com","casinobonus.com","casinobrains.com",
    "casinochief.com","casinocountdown.com","casinodays.com","casinodee.com","casinodome.com",
    "casinoempire.com","casinoforum.com","casinogap.com","casinoguide.com","casinoinn.com",
    "casinojungle.com","casinoking.com","casinolead.com","casinomoon.com","casinonation.com",
    "casinooasis.com","casinopanda.com","casinopedia.org","casinopop.com","casinoportal.com",
    "casinopro.com","casinoqueue.com","casinorabbit.com","casinoray.com","casinorepublic.com",
    "casinorobot.com","casinorolling.com","casinoroyal.com","casinorun.com","casinosaga.com",
    "casinosafari.com","casinosam.com","casinoschool.com","casinosecrets.com","casinosenpai.com",
    "casinosmash.com","casinosniper.com","casinosnoop.com","casinospot.com","casinostar.com",
    "casinostrike.com","casinosuomi.com","casinosurfer.com","casinosweden.com","casinoswiss.com",
    "casinotable.com","casinoterms.com","casinotoplist.com","casinotopia.com","casinotrack.com",
    "casinotrain.com","casinotrends.com","casinotricks.com","casinotrip.com","casinotrust.com",
    "casinoturbo.com","casinouk.com","casinouno.com","casinoup.com","casinousb.com",
    "casinovault.com","casinoventura.com","casinovibe.com","casinovip.com","casinovisit.com",
    "casinovista.com","casinowiki.com","casinowinner.com","casinowins.com","casinowise.com",
    "casinoworld.com","casinozone.com","vegascasino.com","vegasexperience.com","vegasflash.com",
    "vegasgames.com","vegasgold.com","vegasland.com","vegasloop.com","vegasmobile.com",
    "vegaspalm.com","vegasparadise.com","vegasplay.com","vegasplaza.com","vegasplus.com",
    "vegaspop.com","vegaspro.com","vegasrich.com","vegasrush.com","vegasspin.com",
    "vegasstar.com","vegasstrike.com","vegasstyle.com","vegassuper.com","vegastheme.com",
    "vegastrip.com","vegasultimate.com","vegasunit.com","vegasvibe.com","vegasvip.com",
    "vegasway.com","vegaswild.com","vegaswin.com","vegaswins.com","vegasworld.com",

    # === MORE SPORTS BETTING AFRICA / ASIA ===
    "sportpesa.tz","sportpesa.ug","odibets.ke","odibets.tz","odibets.ug",
    "betin.tz","betin.ug","betin.gh","bangbet.ke","bangbet.tz",
    "merrybet.ng","lionsbet.ng","betboro.ng","sportybet.ng","sportybet.ke",
    "sportybet.tz","sportybet.ug","sportybet.gh","sportybet.ci","sportybet.cm",
    "1xbet.ci","1xbet.sn","1xbet.mg","1xbet.cd","1xbet.cg",
    "melbet.ci","melbet.sn","melbet.mg","22bet.ci","22bet.sn",
    "betwinner.ci","betwinner.sn","betwinner.mg","betwinner.cd","betwinner.cg",
    "betpawa.ke","betpawa.tz","betpawa.ug","betpawa.gh","betpawa.rw",
    "betway.rw","betway.mw","betway.bw","betway.na","betway.ls",
    "hollywoodbets.com","hollywoodbets.uk","supabets.com","gbets.com","10bet.ng",
    "accessbet.com","naijabet.com","nigerbet.com","premierbet.ng","betnaija.com",
    "bet9ja.ng","nairabet.ng","bangbet.ng","cloudbet.ng","betika.com",
    "betika.ke","betika.tz","betika.ug","betika.gh","betika.ci",
    "livescore.co.ke","livescore.ng","livescore.gh","livescore.tz","livescore.ug",
    "sbobet.co","sbobet.io","sbobet.mo","sbobet.ag","sbobet.net",
    "maxbet.eu","maxbet.rs","maxbet.ba","maxbet.me","maxbet.mk",
    "mozzartbet.rs","mozzartbet.ke","mozzartbet.gh","mozzartbet.tz","mozzartbet.ug",
    "betking.ng","betking.ke","betking.gh","betking.tz","betking.ug",
    "predictionsports.com","soccerpredictions.net","soccervista.net","predictor.com","tipster.com",
    "betting.co.za","betting.com.ng","betting.co.ke","betting.com.gh","betting.co.tz",
    "safaribet.co.za","punterslounge.com","betgr8.com","wbet.co.za","worldsports.co.za",

    # === CRICKET EXTRAS ===
    "howstat.com","cricketarchive.com","cricket365.com","cricheroes.in","cricketbuzz.com",
    "bigbash.com.au","cplt20.com","ipl.com","psl-cricket.com","bangladeshl-cricket.com",
    "srilankapremierleague.com","afghanistancricket.af","zimbabwecricket.zw","uskpremierleague.com","canadacricket.com",

    # === GOLF EXTRAS ===
    "golfweek.com","golfdigest.com","golf.com","golfchannel.com","golfmagic.com",
    "bunkered.co.uk","golf365.com","golfwrx.com","swingbyswing.com","golfmonthly.co.uk",
    "americangolfer.com","mygolfspy.com","golfindustrycentral.com.au","golfaustralia.org.au","asiantour.com",
    "koreantourgolf.com","japangolfassociation.or.jp","pgaindia.org","arabgolf.com","africangolftour.com",

    # === ATHLETICS EXTRAS ===
    "swimswam.com","worldaquatics.com","paralympic.org","specialolympics.org","deaflympics.com",
    "masters-athletics.org","worldmastersgames.com","maccabiah.com","commonwealthgames.com","asiangames.com",
    "panamericangames.org","africanunion-sports.org","europeanolympics.org","mediterraneangames.org","pacificgames.org",

    # === FINAL BATCH ===
    "bet.co.za","sportsbetting.co.za","tombola.com","winkbingo.com","heartbingo.com",
    "foxybingo.com","meccabingo.com","galabingo.com","pokerstars.sport","pokerstars.casino",
    "betfair.casino","williamhill.casino","paddypower.casino","ladbrokes.casino","coral.casino",
    "skybet.casino","betway.casino","unibet.casino","bet365.casino","888.casino",
    "mrgreen.casino","leovegas.casino","casumo.casino","nordicbet.casino","betsson.casino",
    "lootbet.com","loot.bet","csgolounge.com","skinwallet.com","tradeit.gg",
    "skinbaron.de","buff163.com","dmarket.com","skinport.com","bitskins.com",
    "csfloat.com","swapgg.com","skinswap.com","lootfarm.com","waxpeer.com",
    "betcity.nl","betcity.be","betcity.de","jacks.nl","toto.nl",
    "lotto.nl","bingoal.be","bingoal.nl","betfirst.be","goldenpalace.be",
    "circus.be","napoleon.be","ladbrokes.be","betway.be","unibet.be",
    "bet365.be","bwin.be","888sport.be","1xbet.be","22bet.be",
    "parimatch.be","melbet.be","betwinner.be","megapari.be","mostbet.be",
    "betandyou.be","20bet.be","ivibet.be","betmaster.be","spinbetter.be",
    "bwin.ch","bet365.ch","unibet.ch","betway.ch","ladbrokes.ch",
    "william-hill.ch","888sport.ch","betfair.ch","1xbet.ch","22bet.ch",
    "melbet.ch","betwinner.ch","megapari.ch","mostbet.ch","parimatch.ch",
    "netbet.ch","betsson.ch","nordicbet.ch","casumo.ch","mrgreen.ch",
    "leovegas.ch","rizk.ch","dunder.ch","guts.ch","comeon.ch",
]

DOMAINS = list(dict.fromkeys(DOMAINS))
print(f"Toplam {len(DOMAINS)} domain hazır")
